### ISSUE TITLE
Support multiple database backends

### ISSUE THREAD

**Issue by Hirevo** [Hirevo/alexandrie#1]
Currently, only MySQL is supported as the backing database of Alexandrie.  
To make Alexandrie deployable in more environments, we should offer different database options.  

The options to support I am thinking about are:
- MySQL
- SQLite
- PostgreSQL

Related things to also decide:
- Which should be the default choice ? Should we even have a default for this ?
- Should the same binary able to switch between those without recompiling ?

**Comment by Hirevo** [comment]
I have assigned this to myself, as I have looked into this and have got a prototype working surprisingly well in the `feature/database-backends` branch.  
A PR for discussing this prototype is on its way.

**Comment by kellytk** [comment]
I'd use the SQLite backend if it were available.

**Comment by Hirevo** [comment]
@kellytk
The PR for this (#2) is very very close from being merged.  
It includes the support of MySQL, SQLite and PostgreSQL, so you'll be all set. 🎉  
The implementation is complete, It is just waiting a bit for some review and possibly more documentation.  
I think it will be merged, at worse, by the end of next week (if the implementation were to be revised).

**Comment by kellytk** [comment]
Regarding a default backend, I would default to none if possible.  If a backend is required, I would default to SQLite.

**Comment by Hirevo** [comment]
@kellytk  
I tend to agree with you, there are no defaults for this anymore.  
My worry with this originally was that the compiler emitted a lot of errors in addition to the custom one we emit to alert the user, so it could be hard to spot why the build fails for someone who just cloned and build right away.  
Some changes were made and this is no longer an issue, so I am on board. :tada:

**Comment by kellytk** [comment]
@Hirevo Is it true that Alexandrie can be used without any database backend?

**Comment by Hirevo** [comment]
@kellytk Sadly, no, it requires at least one.  
Something we could do in the future, tho, is support any kind of database-like type to serve as the backend (with a trait, similar to `Store` and `Indexer`), so that we can have (optionally) 100% in-memory replacements for databases.  
But we're not there yet.  
Having no defaults just means that the user is forced to explicitly choose one backend (avoiding making any assumptions about the user's stack).

**Comment by kellytk** [comment]
@Hirevo What I do in that scenario is default to SQLite.  IMHO the default install should be both usable and simple to configure.

**Comment by Hirevo** [comment]
@kellytk The more I think about it, the more I reconsider having no defaults.  
It's true that being introduced with a compile error isn't a very nice experience and SQLite seems like the most suitable default option (lightweight and no friction on database creation).  

Also, do you think we should go with `:memory:` or a saved file as the default connection URL ?  
It's unclear to me which is the most expected as a default (being ephemeral with `:memory:` might be surprising, not really sure tho).

**Comment by kellytk** [comment]
@Hirevo I'm not familiar with how Alexandrie's designed.  What are the benefits of persistence?

**Comment by Hirevo** [comment]
@kellytk Since the storage of crate tarballs and metadata are persistent, having the database be ephemeral could lead to inconsistencies and weird application states.  
Also, created users wouldn't persist.
I would lean to use a filename like `alexandrie.db` as the default connection URL to avoid these issues.

**Comment by kellytk** [comment]
@Hirevo I would use a default filename as you suggest, as well as allow for a path to be provided via a configuration file, CLI input, and environmental variables.

**Comment by Hirevo** [comment]
@kellytk The `alexandrie.toml` configuration file makes configuring the path possible.  
Making a filename a default just means that it is the name found in the configuration file after just having cloned the repository.

**Comment by Hirevo** [comment]
I think we are ready to merge this.  
It has been pretty stable in my own testing.  
We should set up some GitHub Actions to have automated testing against all supported backend but I think it is a bit too much for the scope of this PR.
