### ISSUE TITLE
Is it repository Deprecated? Is the code still updated?

### ISSUE THREAD

**Issue by baoyachi** [Hirevo/alexandrie#100]

**Comment by baoyachi** [comment]
@Hirevo

**Comment by Hirevo** [comment]
Hi !

I have indeed been inactive on this project for far too long, I am very sorry about this.  
I have made a [**more written-out apology here**](#104) but the gist of it is still that I really had no excuse for disappearing like this.
I hope it didn't cause any troubles, and we're now picking this project back up.

Thanks for caring about the project and sorry about me letting you down.
