### ISSUE TITLE
[Question] Why rust-nightly?

### ISSUE THREAD

**Issue by Geobert** [Hirevo/alexandrie#13]
Hi,

I'm looking into alexandrie because we need a private registry at work and I noticed it needs Rust nightly to build. why is that?

**Comment by dutchmartin** [comment]
Looking at the cargo.toml, I see that Tide is used as a web framework. Tide uses the async-await feature that will become stable in the next major release. But theoretical you could try to build ist with the beta compiler.
Maybe I've missed something, but that's what i guess

**Comment by Hirevo** [comment]
Yes, the main blocker for compiling on stable is the usage of async-await.  
There is also some (very) little use of both the `try_blocks` and `inner_deref` (for `Option::as_deref`) feature gates, but those can be very easily replaced by stable constructs.

**Comment by Geobert** [comment]
Thank you for your answers!
