### ISSUE TITLE
Doesn't build on Windows

### ISSUE THREAD

**Issue by Geobert** [Hirevo/alexandrie#14]
Hi again,

I'm on Windows 7 at work and try to dockerize alexandrie.
Before doing anything, I tried to build it and ended with 
```
  = note: LINK : fatal error LNK1181: cannot open input file 'sqlite3.lib'


error: aborting due to previous error

error: Could not compile `migrations_macros`.
```

I understand it needs sqlite library, but I thought it would be pulled as a dependency of the package?

**Comment by dutchmartin** [comment]
There are C dependencies used by the ORM alexandrie uses, cargo does not download those, so you should install the sqllite library yourself. [source](https://diesel.rs/guides/getting-started/)

**Comment by Geobert** [comment]
Thanks for your answer! :D
