### ISSUE TITLE
[Question] How alexandrie update the crate-index?

### ISSUE THREAD

**Issue by Geobert** [Hirevo/alexandrie#15]
Hi me again!

I manage to build a docker image with alexandrie ([Dockerfile here](https://github.com/Hutchison-Technologies/alexandrie/blob/docker/Dockerfile)) but I'm still wondering how some things are supposed to work.

I understand we need a git repo to store the crate-index, and  when looking at crates.io one, there a lot of thing on the github repo.

What do I need to do?
Only the config.json file and `alexandrie` will populate our private github repo?

And on the `[index]` section, what other `type` are available?

**Comment by Hirevo** [comment]
Hi !

Better documentation is definitely needed for this and should come very soon (tracked by **#6**).  

Yes, you're totally right, you only need to create a `config.json` file manually.  
Alexandrie will take care of creating the directories as needed (when crates are published).  

For the `[index]` section, the supported types are the variants of the `Index` enum ([**found here**](https://github.com/Hirevo/alexandrie/blob/master/src/index/mod.rs#L18)).  
Each variant in that enum is a different index manager.  
So, the `type` field is the name of the chosen variant (in kebab-case).  
And, depending on the `type` chosen, the other fields available are those of the struct stored in the variant.  
Currently, only `type = "command-line"` is supported and the fields for it can be [**found here**](https://github.com/Hirevo/alexandrie/blob/master/src/index/cli.rs#L17).  

Using `type = "command-line"` requires having the `git` command to be available through the command line.  
Implementing more ways to manage the index, including using `libgit2` to not depend on the `git` command, is on the roadmap and tracked by **#8**.

**Comment by Geobert** [comment]
Thanks for your answer !

What I don't understand, is how alexandrie has permission to write to the githab crate-index :)

PS: (I'm from Epita :D promo 2002)

**Comment by Hirevo** [comment]
Alexandrie basically doesn't do anything related to push permissions.  
The "command-line" index manager makes changes to a local clone of the index and assumes the `git` command is configured to be able to push to the remote repository (by having the necessary ssh keys configured, for example).  
So, if doing a manual `git push` on the command line would work, then it will work for Alexandrie too.  

Sorry for the delayed response.

PS: Ah, very nice fun-fact. Hi from Epitech (promo 2021) ! 🙋🏽‍♂️

**Comment by Geobert** [comment]
Oh I understand now, it's doing push, and we need the command line to be configured…
So I need to adapt my Docker image to do that. Thank you!
