### ISSUE TITLE
Hide login and register buttons if they are disabled

### ISSUE THREAD

**Issue by CrabeDeFrance** [Hirevo/alexandrie#179]
Hello !

First of all, thanks for the amazing work done with Alexandrie.

I would like to propose you this minor change : I think it is better to hide "login" and "register" buttons if they are not available, instead of being able to click on them and go to a white page.

Please review the MR and integrate it if this is OK for you.

Best regards

**Comment by Hirevo** [comment]
Hello !  
This is indeed a good idea, I'm completely on board with this.  
Thank you for the proposition and for coming up with an accompanying PR, I really appreciate it !
