### ISSUE TITLE
containerised deployments

### ISSUE THREAD

**Issue by danieleades** [Hirevo/alexandrie#26]
I have some questions about the deployment- specifically whether you've looked at containerisation tools such as Docker?

The use case would be to have a docker-compose file that could be used to spin up a functional, load-balanced instance of the registry server- including the database- with a single command. This would ease the friction of getting a server up and running for potential end-users.

I'd love to help, if i can! Making the adoption easier would be a big step towards getting companies and individuals to start using private registries

**Comment by danieleades** [comment]
if this is something you'd be interested in doing i would suggest 2 approaches-

- a single docker container containing a complete installation with sensible backend choices and defaults which can be started with a single command- `docker run xxxx`. useful for testing and prototyping.
- a more modular and configurable approach using docker-compose to create multiple services for each of the components. This would be the production-ready deployment

compare for example https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker  vs https://github.com/tiangolo/full-stack-fastapi-postgresql

**Comment by danieleades** [comment]
a bit of context-
I'm evangelising Rust at the company I work at, but uptake is difficult for us because of security requirements. A private, self-hosted crate registry is a must, and if i could get to that point just by running `docker-compose up`, that'd make my whole month.
I suspect there's a lot of people out there in a similar position.

**Comment by Hirevo** [comment]
Yes, I completely agree that having an easy way to start a fully-working dockerized instance of Alexandrie would be very useful and would increasing adoption.  
So, maybe we could have a 'demo' image of Alexandrie with lightweight defaults, just for testing and we could probably look into using something like [**kickstart**](https://github.com/Keats/kickstart) to allow scaffolding custom production-ready docker setups.  
I'll look into this in the following days, and will come back with some feedback of how it went.  
Feel free to experiment as well and/or make feedback on the work that will happen for this issue.

**Comment by danieleades** [comment]
That's brilliant! If I can contribute, I will

**Comment by Hirevo** [comment]
**Very good news :tada::**  
@bmhenry has been working on a great PR (**#28**) to address this issue, providing an easy way to start a containerized instance, for SQLite, PostgreSQL and MySQL.  
It has now been merged with docs, in both the README and the user guide, of how to get started with them.  
He has done way better than what I would have done, for sure, so thanks again @bmhenry.
