### ISSUE TITLE
[Question] Can this crate afford to be more opinionated?

### ISSUE THREAD

**Issue by danieleades** [Hirevo/alexandrie#39]
I don't know if this is the forum for questions like this.

I like that this crate is attempting to be very exensible, and Rust provides some nice ways to support this through traits. But I wonder if there's a couple of places that this is not adding value? For example this crate supports two indexing strategies out of the box-
- a command line based module which shells out to git
- a libgit2-based module

I can't see why you would ever need both?

I see that you want to add a 'remote index' implementation. I think this has questionable value (since you can always use a remote index as your upstream git repository!) but it's cool that the option exists. But i can't see why you would ever want two different strategies to manage a local index, unless each one represented a different set of *trade-offs*. If one is simply better than the other, why support both?

**Comment by danieleades** [comment]
i guess this is kind of a duplicate of #41

**Comment by bmhenry** [comment]
I'm not an expert on the matter, but what I've seen from using `crates.io` is that often one won't support a feature the other does. For example, using libgit2 doesn't require that `git` is installed locally, which is nice when using it from a minimal system (or docker :wink:). But unfortunately, last I tried libgit2 couldn't handle using SSH URLs piped through the system's ssh-agent, rendering the libgit2 implementation useless in the case of (for example) GitHub Enterprise for organizations that require using SSH keys for pulls.

I'm not the author, so I'll just leave my two cents: Assuming the above is true (and please correct me if I'm wrong), and given the fact there are *very* few other registry implementations right now, I think it would be nice to keep both git implementations for now.

**Comment by danieleades** [comment]
Thanks for the perspective!

I'm quite surprised you can't get the SSH authentication you're looking for with libgit2

**Comment by danieleades** [comment]
i'll close this for now. I still think the crate can be restructured to use both git implementations a little better. I've made a pull request with some tiny refactors (#38), and opened an issue to discuss a possible restructure of the `Index` (#41)
