### ISSUE TITLE
Support for LDAP as an authentication source

### ISSUE THREAD

**Issue by baoyachi** [Hirevo/alexandrie#80]
just like this link:[https://www.jfrog.com/confluence/display/JFROG/LDAP](https://www.jfrog.com/confluence/display/JFROG/LDAP)

**Comment by Hirevo** [comment]
I personally never interacted with LDAP before, and I don't know how any of it works and how to use it effectively for authentication.  
But I take note that bringing support for external sources of authentication in Alexandrie is something that would be beneficial, with [**support for OAuth**](https://github.com/Hirevo/alexandrie/issues/57) having been requested as well.  
I'll have to see what I can do to support these things effectively.  
Thank you for filing the issue !
