### ISSUE TITLE
Wrong error while performing the migrations for PostgreSQL

### ISSUE THREAD

**Issue by HugoPuntos** [Hirevo/alexandrie#94]
Hello,

While performing the migrations for PostgreSQL, the following error occurs:

```
Failed with: Invalid migration directory, the directory's name should be <timestamp>_<name_of_migration>, and it should only contain up.sql and down.sql
```

It seems to come from the following [line](https://github.com/Hirevo/alexandrie/blob/master/docker/startup.sh#L67):

```
elif [ "${DATABASE}" = "postgresql" ]; then
```

which should be:

```
elif [ "${DATABASE}" = "postgres" ]; then
```

I also noticed some kind of confusion between the existing repository `docker/postgres` and `docker/postgresql` that doesn't exist. In the [documentation](https://github.com/Hirevo/alexandrie/blob/master/docs/src/whats-available/docker.md#user-configuration), the `docker/postgresql/rootpass.txt` path is mentioned but IMHO, it should be `docker/postgres/rootpass.txt`.

Same remark for these lines:
- https://github.com/Hirevo/alexandrie/blob/master/docker/postgres/postgres-compose.yaml#L5
- https://github.com/Hirevo/alexandrie/blob/master/docker/postgres/postgres-compose.yaml#L40

Since I don't have the privilege to open a PR, I duplicated the repository and I created a PR to show you the changes: https://github.com/HugoPuntos/alexandrie/pull/2.

Let me know if you want me to open a PR.

**Comment by Hirevo** [comment]
Hi !

Thanks for filing this issue and writing the PR (**#96**) to fix it.
I am sorry about the long wait, it has now been merged into the main branch.

Thanks again for the contribution !
