### ISSUE TITLE
Allow configuring the crate upload size limit 

### ISSUE THREAD

**Issue by tux3** [Hirevo/alexandrie#98]
Hello,

On Crates.io there is a default crate upload size limit of 10MB, but this value is configurable per-crate (and can be raised by the crates.io team on request).  
However, I'm running an instance of Alexandrie where I need to upload large crates,  
and it seems that the `PUT /api/v1/crates/new` endpoint hard-codes a 10MB request size limit:

```rust
// In alexandrie/src/api/crates/publish.rs: async fn put
let mut bytes = Vec::new();
(&mut req).take(10_000_000).read_to_end(&mut bytes).await?;
```

This causes upload requests to fail with mysterious "failed to fill whole buffer" HTTP errors.

Would it be possible to make this size limit configurable instead of hard-coded, and ideally return an explicit error message if the request is too large? 

Thank you! =)

**Comment by somewheve** [comment]
I also got this bug, and I tried to adjust it to 100_000_000, but I got `error: [28] Timeout was reached`.  
My crate contains a lot of other files. So I don't know how to set up it. 
Did you set up it successfully?

**Comment by tux3** [comment]
@somewheve You may want to configure the `http.timeout` option client side, in your `cargo.toml`

**Comment by somewheve** [comment]
wow, I will try it  thank you very much

**Comment by somewheve** [comment]
I try to set it as  600, but also got the problem

**Comment by Hirevo** [comment]
Hello !

Thanks for filing this issue.  
It is true that this limit being hardcoded can be an issue.
I am thinking about starting with making this limit configurable through the configuration file as a quick fix and possibly later think of ways to make it overridable per crate.  
I'll be doing this very soon, sorry for the long wait about this.
